def on_button_pressed_a():
    led.plot(0, 0)
    led.set_brightness(255)
    basic.pause(2000)
    led.plot(1, 1)
    led.set_brightness(255)
    basic.pause(2000)
    led.plot(2, 2)
    led.set_brightness(255)
    basic.pause(2000)
    led.plot(3, 3)
    led.set_brightness(255)
    basic.pause(2000)
    led.plot(4, 4)
    led.set_brightness(255)
input.on_button_pressed(Button.A, on_button_pressed_a)

def on_button_pressed_b():
    led.unplot(4, 4)
    basic.pause(2000)
    led.unplot(3, 3)
    basic.pause(2000)
    led.unplot(2, 2)
    basic.pause(2000)
    led.unplot(1, 1)
    basic.pause(2000)
    led.unplot(0, 0)
input.on_button_pressed(Button.B, on_button_pressed_b)
